// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tsw303005/Dcard-URL-Shortener/internal/dao (interfaces: ShortenerDAO)

// Package daomock is a generated GoMock package.
package daomock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	dao "github.com/tsw303005/Dcard-URL-Shortener/internal/dao"
)

// MockShortenerDAO is a mock of ShortenerDAO interface.
type MockShortenerDAO struct {
	ctrl     *gomock.Controller
	recorder *MockShortenerDAOMockRecorder
}

// MockShortenerDAOMockRecorder is the mock recorder for MockShortenerDAO.
type MockShortenerDAOMockRecorder struct {
	mock *MockShortenerDAO
}

// NewMockShortenerDAO creates a new mock instance.
func NewMockShortenerDAO(ctrl *gomock.Controller) *MockShortenerDAO {
	mock := &MockShortenerDAO{ctrl: ctrl}
	mock.recorder = &MockShortenerDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShortenerDAO) EXPECT() *MockShortenerDAOMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockShortenerDAO) Get(arg0 context.Context, arg1 *dao.Shortener) (*dao.Shortener, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*dao.Shortener)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockShortenerDAOMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockShortenerDAO)(nil).Get), arg0, arg1)
}

// Shorten mocks base method.
func (m *MockShortenerDAO) Shorten(arg0 context.Context, arg1 *dao.Shortener) (uuid.UUID, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shorten", arg0, arg1)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Shorten indicates an expected call of Shorten.
func (mr *MockShortenerDAOMockRecorder) Shorten(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shorten", reflect.TypeOf((*MockShortenerDAO)(nil).Shorten), arg0, arg1)
}
